<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EmailmemyQuote</name>
   <tag></tag>
   <elementGuidId>77afa006-e15c-4b6c-b0f2-de2c470ccb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='p_lt_WebPartZone3_ZoneA_pageplaceholder_p_lt_WebPartZone3_Zonesecpad_BCL_SuccessPage_Term25EmailMyQuote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='p_lt_WebPartZone3_ZoneA_pageplaceholder_p_lt_WebPartZone3_Zonesecpad_BCL_SuccessPage_Term25EmailMyQuote']</value>
      <webElementGuid>6150a07d-639b-4392-b514-124e45b53ff4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
