<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Recalculate</name>
   <tag></tag>
   <elementGuidId>f5f6c480-5657-4835-9b3d-bd59b68b5a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='recalculateQuote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='recalculateQuote']</value>
      <webElementGuid>cdd963a4-0417-481b-ac25-12f7d8004b3b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
