<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accept and continue</name>
   <tag></tag>
   <elementGuidId>0ebf6180-80dd-4b71-97a3-200202ed9ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnContinueStep1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnContinueStep1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1261f986-5744-4ca6-b6ae-236cfca1fc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33b68aca-a909-45c3-aab1-8bc7c23e1c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnContinueStep1</value>
      <webElementGuid>eef03196-12be-4c9f-bb5e-79b9f55cc6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button next btn-primary</value>
      <webElementGuid>bf2b3089-893b-4b4c-b62f-d7058708d5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept and continue</value>
      <webElementGuid>26a2983a-a553-4ef4-a1b1-35d4ea28c7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnContinueStep1&quot;)</value>
      <webElementGuid>98572cdb-39fc-40c6-a9af-44cd70e660ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnContinueStep1']</value>
      <webElementGuid>90818c51-717d-4b10-8c6c-97061e99c925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard']/div/div[2]/a</value>
      <webElementGuid>a34f01f3-3842-4f4e-a4e1-24b1c6344065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accept and continue')]</value>
      <webElementGuid>4c9acf3f-8569-4433-b8a3-1eb2615e3695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get your quote'])[1]/following::a[1]</value>
      <webElementGuid>83e78ba3-43b3-41aa-8acd-50ab970e4ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter an amount from $10,000 to {%CriticalIllnessMaxValue%}'])[1]/following::a[2]</value>
      <webElementGuid>4405f377-be60-41e4-8197-ec7ff77ab744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline and exit'])[1]/preceding::a[1]</value>
      <webElementGuid>1bd9a5ef-3215-45e4-a315-568ffa600a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::a[2]</value>
      <webElementGuid>597962d1-6de7-4c3f-b6c5-1bdd94590a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/div[2]/a</value>
      <webElementGuid>3e90bf05-24a6-44ed-8050-89c452dfe8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'btnContinueStep1' and (text() = 'Accept and continue' or . = 'Accept and continue')]</value>
      <webElementGuid>04205b6f-174f-49bb-b30b-cb0fcc934fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
