<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue</name>
   <tag></tag>
   <elementGuidId>0bf41959-2fcc-47fe-8a51-20d46f3a68c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnContinueStep1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnContinueStep1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d4d9ce3-c32e-4698-b06e-a8e8e5d3cf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>356a844f-93df-4ca0-a3b3-bffa40d0bdb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnContinueStep1</value>
      <webElementGuid>82e514ec-ff00-4177-b95a-81ea4e281501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button next btn-primary</value>
      <webElementGuid>c4c84807-0502-4bc3-ae7c-5649f1d2d776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>996ac2c6-fe89-44d9-996c-e65034c44de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnContinueStep1&quot;)</value>
      <webElementGuid>f8f28523-426b-4bba-87c7-c7e9a08f5ae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnContinueStep1']</value>
      <webElementGuid>8805dba6-ba3e-4313-a44b-6d5c118dfcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard']/div/div[2]/a</value>
      <webElementGuid>573311de-2221-4a4d-83fe-3538b427438c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Continue')])[2]</value>
      <webElementGuid>4dfbc0c8-cca7-4bb5-bd92-5b5b269480c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get your quote'])[1]/following::a[1]</value>
      <webElementGuid>52c69768-705c-47c2-a686-fcc8577b92e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter an amount from $10,000 to {%CriticalIllnessMaxValue%}'])[1]/following::a[2]</value>
      <webElementGuid>3f9328b2-754b-4ca9-88b3-e8480ab96db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline and exit'])[1]/preceding::a[1]</value>
      <webElementGuid>6efbc66e-1bb4-466b-8b5e-5b32825530a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::a[2]</value>
      <webElementGuid>d5032946-0ffd-425d-ba18-f29585bfd8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/div[2]/a</value>
      <webElementGuid>d6f4ad4e-0308-4da6-a5a0-2c5e162c5903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'btnContinueStep1' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>692d0c0d-1ae1-48c6-8612-c7eb60ac6a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
