<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_arrow_forward</name>
   <tag></tag>
   <elementGuidId>5f4419fa-7809-4c2e-bd80-7e0cac89cf39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c5ff0e5-365d-41a9-b3fc-d417e49fcba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>880ae2db-8e13-4906-ad6f-31ae15890e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>ef487055-446b-4da8-aba4-6a2471d2d49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>eaa8234b-51ca-4847-ba1d-ce5361f91a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-flat-button mat-button-base mat-secondary ROUNDEDCTA ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>5abd712c-563e-40f6-b831-5ca5e5611b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_forward</value>
      <webElementGuid>f8abe220-f284-44ca-b6e4-40e9ab61567b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next&quot;)</value>
      <webElementGuid>e797d32c-e83f-4601-b63d-2e64ed2a37f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>aaf844dc-4d4b-42c6-9f48-d2ea3d273130</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='next']</value>
      <webElementGuid>b564689c-7fd7-49cd-aee5-d54a9db25cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/app-liabilities/form/app-wizard-nav/div/div/button[2]</value>
      <webElementGuid>f3512d3f-2b34-4783-a6e0-118f974d54e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long term debts (5 years of financing left or more)'])[1]/following::button[3]</value>
      <webElementGuid>021bae68-e23f-478d-a082-2da4af9e0706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'next', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>e0ee7b60-31a2-4d3b-be92-9e898f90e71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f3f9df9e-9608-4ce7-91f7-9bec3b607b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'next' and @type = 'submit' and (text() = 'arrow_forward' or . = 'arrow_forward')]</value>
      <webElementGuid>3ca95a2f-acb2-4a1a-b67f-8ae2cbafe1d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
