<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1</name>
   <tag></tag>
   <elementGuidId>bf55c3d2-cd8b-43ba-a5e5-8f62781442d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='navButton_1'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d54b6805-9e6b-43f6-ad7e-7ef4ceb97400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78f16c34-6ae6-437b-ac4f-5144ed1322c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navButton_1</value>
      <webElementGuid>669b8ec6-47d8-4b83-9490-2b3b32fb8f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator ml-2 mr-2 mt-2 btnChoice mat-raised-button mat-button-base ROUNDED cdk-focused cdk-mouse-focused</value>
      <webElementGuid>6f8997c3-ed3e-42a9-aecb-6560931303d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4db4cfb6-7512-4749-8e34-2e240348df28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dependent-container&quot;)/app-btn-choice[@class=&quot;ng-tns-c90-10 ng-star-inserted&quot;]/button[@id=&quot;navButton_1&quot;]</value>
      <webElementGuid>beb0eba4-84f0-429a-a1ba-b733e4589147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>9d0082ad-4e16-4a7f-93f8-c2b0146cf37d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='navButton_1'])[6]</value>
      <webElementGuid>d7eeb7cb-6e52-4eb6-b103-c844435a351a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dependent-container']/app-btn-choice[2]/button</value>
      <webElementGuid>0bd9a217-22fe-4475-bc96-ba3a7465f0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How many dependents do you have?'])[1]/following::button[3]</value>
      <webElementGuid>39b2f403-024b-468e-9e3c-61516dec5ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In a relationship with children'])[1]/following::button[3]</value>
      <webElementGuid>02fd9a98-69f9-4d78-b38b-80c2d70edf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-btn-choice[2]/button</value>
      <webElementGuid>b53592b8-61b9-4078-a343-318f87501511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'navButton_1' and (text() = '1' or . = '1')]</value>
      <webElementGuid>5287c4e6-8c2e-4c59-91cf-605c12ba4b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
