<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_START</name>
   <tag></tag>
   <elementGuidId>f761283a-d934-4f4f-ab4c-6fdc7a24b77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='startbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ae88d65-4ec9-4771-b9c1-a914c90fe63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startbtn</value>
      <webElementGuid>e347c934-ec14-45c2-b878-b6f33d2af86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d3a983fd-38ce-47ea-bc22-1be301931127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>6c538366-e8b6-49dc-a91b-970c58c92837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-raised-button mat-button-base mat-secondary ROUNDEDCTA cdk-focused cdk-mouse-focused</value>
      <webElementGuid>7ee5d2b0-77fd-4c4b-a82f-be42b1b33b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> START </value>
      <webElementGuid>6884be01-5966-470c-b862-d4357899afa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startbtn&quot;)</value>
      <webElementGuid>5d25c16d-c90a-4711-95ea-6986427f1017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>482dcf1f-c29e-42f8-bc1d-ed824fb0fd4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='startbtn']</value>
      <webElementGuid>b74ffe2b-9fab-453e-81a6-e0ed6c1770a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-start']/div/button</value>
      <webElementGuid>6bbdf455-97e3-4caa-8876-cfdfadecedd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'startbtn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>87968451-60e1-4440-926b-45caaf19fa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2beab90a-1a60-44dc-a27a-f2c6742fccf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'startbtn' and @type = 'submit' and (text() = ' START ' or . = ' START ')]</value>
      <webElementGuid>5b8b696f-f706-4c6d-9f59-c9290e97f3c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
