<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Liquid debts</name>
   <tag></tag>
   <elementGuidId>2d168ca4-f9c1-41e6-bba8-a52a26c176eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c26-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/app-liabilities/form/div/div/div/app-number-input/div/div/mat-form-field/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa287057-6eac-45ea-9031-efd5837ddbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c26-3</value>
      <webElementGuid>0caa5513-4ada-42a6-817e-cd307098d016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liquid debts</value>
      <webElementGuid>d81220b4-f40e-461d-8f6a-d5ace101ff18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card-content ml-0 mr-0 ml-lg-5 mr-lg-5 p-3&quot;]/app-liabilities[@class=&quot;ng-tns-c111-2 ng-star-inserted&quot;]/form[@class=&quot;flexgrow ng-tns-c111-2 ng-trigger ng-trigger-fadeInAnimation ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;flexgrow ng-tns-c111-2&quot;]/div[@class=&quot;row ng-tns-c111-2&quot;]/div[@class=&quot;col text-center ng-tns-c111-2&quot;]/app-number-input[@class=&quot;ng-tns-c111-2&quot;]/div[@class=&quot;row ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;col-12 ng-star-inserted&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c26-3 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c26-3&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c26-3&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c26-3&quot;]</value>
      <webElementGuid>f47d7761-fe8d-4fca-8c3d-bffb7823c8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>315bb22f-bb9b-49ff-a894-59d8268d7646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/app-liabilities/form/div/div/div/app-number-input/div/div/mat-form-field/div/div/div[4]</value>
      <webElementGuid>8940fe81-f685-43c5-9718-edb7cc1b717f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✗ Exclude'])[1]/following::div[16]</value>
      <webElementGuid>f72b8855-76b3-4142-a125-bd587c73b2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>6879f0e8-77be-4bb5-9fe9-eb22ffc562d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Liquid debts' or . = 'Liquid debts')]</value>
      <webElementGuid>7f5787c7-b278-432f-a8ca-8c35c43dfcb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
