<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_monthly income</name>
   <tag></tag>
   <elementGuidId>1e8bc6a4-df96-4b02-b9ed-b096bf645d2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c26-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/app-monthly-income/form/div/div/div/app-number-input/div/div/mat-form-field/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de9f799b-c3d7-48ad-a1ba-c9c8feb031e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c26-12</value>
      <webElementGuid>a2b687b0-062f-4c5b-8b36-5dca3451891e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>monthly income</value>
      <webElementGuid>bc4de6f6-1c94-4a65-8c74-808d4a351541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card-content ml-0 mr-0 ml-lg-5 mr-lg-5 p-3&quot;]/app-monthly-income[@class=&quot;ng-tns-c123-11 ng-star-inserted&quot;]/form[@class=&quot;flexgrow ng-tns-c123-11 ng-trigger ng-trigger-fadeInAnimation ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;flexgrow ng-tns-c123-11&quot;]/div[@class=&quot;row ng-tns-c123-11&quot;]/div[@class=&quot;col text-center ng-tns-c123-11&quot;]/app-number-input[@class=&quot;ng-tns-c123-11&quot;]/div[@class=&quot;row ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;col-12 ng-star-inserted&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c26-12 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c26-12&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c26-12&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c26-12&quot;]</value>
      <webElementGuid>0ee361c8-870c-4171-9cd0-fd7a4454bcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>b847c221-d9d0-4b56-81bb-cfc53256ab8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/app-monthly-income/form/div/div/div/app-number-input/div/div/mat-form-field/div/div/div[4]</value>
      <webElementGuid>52c4d83a-7789-4122-87b7-6aeed6a7654e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your net monthly income?'])[1]/following::div[16]</value>
      <webElementGuid>304ff9b0-5cdf-4e88-9b89-15fe20d4868e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>2c4c33f2-68b0-414b-93b3-8eff215540b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'monthly income' or . = 'monthly income')]</value>
      <webElementGuid>89a3b82f-4322-4ca9-ade0-c09d1d11b34f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
