<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Long term debts (5 years of financing l_d27507</name>
   <tag></tag>
   <elementGuidId>84704fe8-d539-412e-b94a-027660b110b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c26-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/app-liabilities/form/div/div[3]/div/app-number-input/div/div/mat-form-field/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b606008-7281-4230-9da0-2de644034c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c26-5</value>
      <webElementGuid>57e74a84-ed0f-4a3d-bc96-51c86047423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Long term debts (5 years of financing left or more)</value>
      <webElementGuid>d516e66f-ef42-4d9b-9c03-ef46e6f69f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card-content ml-0 mr-0 ml-lg-5 mr-lg-5 p-3&quot;]/app-liabilities[@class=&quot;ng-tns-c111-2 ng-star-inserted&quot;]/form[@class=&quot;flexgrow ng-tns-c111-2 ng-trigger ng-trigger-fadeInAnimation ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;flexgrow ng-tns-c111-2&quot;]/div[@class=&quot;row ng-tns-c111-2&quot;]/div[@class=&quot;col text-center ng-tns-c111-2&quot;]/app-number-input[@class=&quot;ng-tns-c111-2&quot;]/div[@class=&quot;row ng-valid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;col-12 ng-star-inserted&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c26-5 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c26-5&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c26-5&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c26-5&quot;]</value>
      <webElementGuid>21a7a5d0-13a4-4b77-a5d0-44cb52eee7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>a623d191-bce9-487f-af5a-56a64adac633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/app-liabilities/form/div/div[3]/div/app-number-input/div/div/mat-form-field/div/div/div[4]</value>
      <webElementGuid>ef307394-26d0-4219-9fef-47a211ca011f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short term debts (under 5 years of financing left)'])[1]/following::div[19]</value>
      <webElementGuid>f709250a-cea0-43d8-823c-5ac15a6d3abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/app-number-input/div/div/mat-form-field/div/div/div[4]</value>
      <webElementGuid>ba290c61-8a42-4b5d-907e-d0d6660bdcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Long term debts (5 years of financing left or more)' or . = 'Long term debts (5 years of financing left or more)')]</value>
      <webElementGuid>0549230f-db33-42f0-8ea1-07cf429bc93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
