<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close_tks-dialog-body</name>
   <tag></tag>
   <elementGuidId>96a2b42a-9921-454e-9dff-ae9788f707e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.tks-dialog-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9fc3e825-90bb-465f-a420-2ffa5c1ca633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tks-dialog-body</value>
      <webElementGuid>91daa9bf-6190-43ea-8da1-99cb60d34a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assomption-needs-analysis-qa.lavvi.com/bluecrosslifeinsurance?embedded=1&amp;lang=en-CA&amp;id=527df476-a941-4f52-8476-f6ed4afe33cc</value>
      <webElementGuid>7a269f4e-c5bb-4b58-aea3-547d57c5392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a41d1672-fe6d-4266-b558-c6367344374f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;modernizr-sizes modernizr-supports modernizr-srcset modernizr-serviceworker modernizr-touchevents&quot;]/body[@class=&quot;LTR Chrome ENUS ContentBody&quot;]/div[@class=&quot;tks-dialog-modal-background&quot;]/div[@class=&quot;tks-dialog&quot;]/iframe[@class=&quot;tks-dialog-body&quot;]</value>
      <webElementGuid>4bb7f777-2d50-48e0-a0e2-200139d9a02d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>563eaedb-97ac-4a97-9ae0-6904701135a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://assomption-needs-analysis-qa.lavvi.com/bluecrosslifeinsurance?embedded=1&amp;lang=en-CA&amp;id=527df476-a941-4f52-8476-f6ed4afe33cc']</value>
      <webElementGuid>12ce7b5a-5aa8-42b2-b238-e3fa6038f1f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
