<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__longTerm</name>
   <tag></tag>
   <elementGuidId>e07afd7d-a11f-45a2-b2f7-3764a4e7061b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#longTerm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='longTerm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>152ad85e-0cca-4479-9327-b2948f7fd97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c26-5 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>1a7d41aa-ae7f-4bd6-ba7e-64b4a88c1e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>longTerm</value>
      <webElementGuid>baaf7475-68d6-473c-8d41-185034ca88c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Long term debts (5 years of financing left or more)</value>
      <webElementGuid>331ff461-d469-45e7-859b-a26490ce0b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d42143b-fc47-40d5-bee6-e33ef8fdfdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c1312da-b48e-42bd-8f85-9df4e81d5d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>5af9fcc8-0f28-4883-b54a-e08383dbf80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>4f3ee9b0-697d-402d-8447-cfa029955a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Long term debts (5 years of financing left or more)</value>
      <webElementGuid>28d662e9-39e7-4768-8097-debf39d1d65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;longTerm&quot;)</value>
      <webElementGuid>6889beb5-9590-4288-be67-efdce2194924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>c8312b1f-d7c7-4b58-93d9-2ad2878961a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='longTerm']</value>
      <webElementGuid>e7ffd4b4-bf2b-4cc1-9dad-ab3d921c43dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/app-liabilities/form/div/div[3]/div/app-number-input/div/div/mat-form-field/div/div/div[4]/input</value>
      <webElementGuid>06274d64-71af-4c8e-afeb-01a7eabf8aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/app-number-input/div/div/mat-form-field/div/div/div[4]/input</value>
      <webElementGuid>4ed40431-f302-4b84-917f-b1eb3835b44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'longTerm' and @placeholder = 'Long term debts (5 years of financing left or more)']</value>
      <webElementGuid>930d7994-f9d8-4027-800c-5a2d7e9d560f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
