<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shortTerm</name>
   <tag></tag>
   <elementGuidId>57c770a9-d314-485a-8a4e-551362067ab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shortTerm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shortTerm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3d0df9b-e855-4a6b-b752-9009bb84ffc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c26-4 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>18085f19-4592-48c3-957c-6217ba43f681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shortTerm</value>
      <webElementGuid>7a261033-bb50-494d-a0d9-19711f24f26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Short term debts (under 5 years of financing left)</value>
      <webElementGuid>fd3c1b5e-b798-429a-b4ad-6fbc54bf6cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc33d1bb-6309-47d7-9e86-ecd2378abb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cdb631f0-85a9-43d1-b42f-207e13790296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>7c2bd71e-51fc-48c1-b2fd-01e60c28ac15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>cd6bb203-6b5e-4622-a6ca-603d59cbb74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Short term debts (under 5 years of financing left)</value>
      <webElementGuid>78cf762d-b021-4885-9074-69254294ab66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shortTerm&quot;)</value>
      <webElementGuid>00f8fbd5-00da-4d1b-9a9e-178b669ea421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BCL/BCL_Landing page/NeedsAnalysis/Page_Term and whole life insurance plans  B_9ccd89/iframe_Close_tks-dialog-body</value>
      <webElementGuid>dfa2129b-bdaf-49f6-b58c-c835fc64c84f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shortTerm']</value>
      <webElementGuid>5ab32c15-48da-48a5-8d91-00c7f8433580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/app-liabilities/form/div/div[2]/div/app-number-input/div/div/mat-form-field/div/div/div[4]/input</value>
      <webElementGuid>328b3f24-b041-42ac-96a2-71556259ef0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/app-number-input/div/div/mat-form-field/div/div/div[4]/input</value>
      <webElementGuid>d5dce682-13cb-4cc6-ae21-a26e5cdea2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'shortTerm' and @placeholder = 'Short term debts (under 5 years of financing left)']</value>
      <webElementGuid>e7a63e71-2f58-4c2c-9895-5815c2ea7b86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
