<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close</name>
   <tag></tag>
   <elementGuidId>2bb46f8e-39e0-4941-b798-e21204076578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exit-popup-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='exit-popup-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31ddeb10-1d91-49db-a687-101af81977bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87afd19b-f1e7-491b-ac46-407617f50e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close_icon</value>
      <webElementGuid>068983a1-5bc1-422f-81f0-1908004e9514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exit-popup-close</value>
      <webElementGuid>cf541870-c93c-4006-8a5c-d590fe7f4204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ×Close</value>
      <webElementGuid>92e2d0f2-586d-4184-8f4d-0382676f9bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exit-popup-close&quot;)</value>
      <webElementGuid>de3741c6-7166-409a-b03c-02b1b023171b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='exit-popup-close']</value>
      <webElementGuid>794526cf-83d0-4ad2-9e2f-80a735073046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ExitPopup_modal']/div/div/div/button/span</value>
      <webElementGuid>e22e7f5d-1927-4f3c-9038-66d4cae63b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[3]/following::span[1]</value>
      <webElementGuid>157430c6-2921-434b-8eb6-b7e564f8fa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success!'])[3]/following::span[1]</value>
      <webElementGuid>813c0093-581b-40f9-a694-38b34db58ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Before you go'])[1]/preceding::span[2]</value>
      <webElementGuid>00291a5d-7cb9-4506-bfa3-617e885a5015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/button/span</value>
      <webElementGuid>0956b865-5f0b-43c7-b1c5-3f183d8508ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'exit-popup-close' and (text() = ' ×Close' or . = ' ×Close')]</value>
      <webElementGuid>a2f47a51-daed-4a0d-b7fb-05b0ec0a89be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
