<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fullname</name>
   <tag></tag>
   <elementGuidId>f356bee7-b932-494c-9b07-cff0628d7582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactAdvisor&quot;]/div/div/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactAdvisor&quot;]/div/div/div[2]/div[1]/input</value>
      <webElementGuid>53cfc219-9895-431a-b7f5-955d7afc3802</webElementGuid>
   </webElementProperties>
</WebElementEntity>
