<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Message</name>
   <tag></tag>
   <elementGuidId>34dcc605-da2a-4377-8e84-dc7a5796a9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactAdvisor&quot;]/div/div/div[2]/div[4]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactAdvisor&quot;]/div/div/div[2]/div[4]/textarea</value>
      <webElementGuid>0a743296-6afe-45e4-9e0e-41ac52fbbe12</webElementGuid>
   </webElementProperties>
</WebElementEntity>
