<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PhoneNumber</name>
   <tag></tag>
   <elementGuidId>b37948d7-67d5-41b8-a171-7b9629ac4477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='modal-content']//input[@id='emailmyQuote-phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-content']//input[@id='emailmyQuote-phoneNumber']</value>
      <webElementGuid>716d1f30-3f7c-466f-9662-a27b4b5de0a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
