<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseExitPopup</name>
   <tag></tag>
   <elementGuidId>cacd011f-8c35-4869-8fbf-bb712e898765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;exit-popup-close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;exit-popup-close&quot;]</value>
      <webElementGuid>a9ede1f5-2d35-43be-8a7c-b158da54e73c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
