<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CriticalIllness</name>
   <tag></tag>
   <elementGuidId>64df470c-8197-4732-bff3-05834d7e4bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='criticalIllnessRiderAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='criticalIllnessRiderAmount']</value>
      <webElementGuid>638d778e-7f3c-40d8-9ee7-3fad0ca6c5df</webElementGuid>
   </webElementProperties>
</WebElementEntity>
