<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_DOB</name>
   <tag></tag>
   <elementGuidId>d7588bda-8a98-4bcf-a65d-fe4258ae367a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Wizardform-Panels&quot;]/div[1]/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Wizardform-Panels&quot;]/div[1]/div[2]/div/label</value>
      <webElementGuid>f2680f6c-0939-420d-93d2-b3a7f7f07230</webElementGuid>
   </webElementProperties>
</WebElementEntity>
