<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_Female</name>
   <tag></tag>
   <elementGuidId>25d53ba0-25de-4276-9feb-56111275b22d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Wizardform-Panels&quot;]/div[1]/div[3]/div/div[2]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Wizardform-Panels&quot;]/div[1]/div[3]/div/div[2]/label[2]</value>
      <webElementGuid>9f1dfd09-e5ce-4301-9c14-010653b565fd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
