<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_Smoker</name>
   <tag></tag>
   <elementGuidId>1470625e-1b3a-4b7c-b868-1a4af71d9fd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Wizardform-Panels&quot;]/div[1]/div[4]/div/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Wizardform-Panels&quot;]/div[1]/div[4]/div/div[1]/label[2]</value>
      <webElementGuid>8892a4a6-a537-4281-9c78-0fd4cbc283dc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
