<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>videoIframe_Video</name>
   <tag></tag>
   <elementGuidId>915b36df-0009-4faa-a47b-6f2030b814e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form&quot;]/section[2]/div/div[1]/div[3]/div/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form&quot;]/section[2]/div/div[1]/div[3]/div/div/div/iframe</value>
      <webElementGuid>82d82ac3-7ae9-4c8d-bb33-7b44209f0b13</webElementGuid>
   </webElementProperties>
</WebElementEntity>
