<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RefID</name>
   <tag></tag>
   <elementGuidId>9cbea0f5-d10c-4d75-9796-b2c433244030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='txtReferenceID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='txtReferenceID']</value>
      <webElementGuid>da9dc157-9c40-42d3-bf1b-301818f0965b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
