<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_TermsofUse</name>
   <tag></tag>
   <elementGuidId>230d9e37-9068-4314-8cac-29b98d9f7cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space()='assomption.ca/en/Terms-of-Use']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space()='assomption.ca/en/Terms-of-Use']</value>
      <webElementGuid>e03b89a5-440b-44ca-800d-b22745ac068d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
