<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ContinueForgotref</name>
   <tag></tag>
   <elementGuidId>09f18fcd-6cf9-412e-9edb-0170e42f2c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='linkContinueRequest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='linkContinueRequest']</value>
      <webElementGuid>222b7001-0488-4fb9-a273-0af074cfb9e1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
